### ISSUE TITLE
Reading a Tierpsy h5 file

### ISSUE THREAD

**Issue by WeiWenKevinChen** [iteal/wormpose#21]
Hi,
I am trying to use your WormPose to analyze the video that contains multiple worms. I first used the Tierpsy to extract the individual worms but I am not sure how to input different worms in the same Tierpsy h5 file to the WormPose. Could you let me know how to do it? Thanks!

**Comment by iteal** [comment]
Hi!
I think you need first to decide if the different worms are similar or different enough visually, so that you can train a network from images of each of them separately or together.
At https://iteal.github.io/wormpose/tierpsy.html there is some information on how to organize the Tierpsy files to use with wormpose.
What we did is one worm per video (two hdf5 files one for images one for features), and several videos to constitute a wormpose dataset.

**Comment by WeiWenKevinChen** [comment]
I see. Thanks for your reply!

**Comment by iteal** [comment]
Actually, only one worm per file is supported at the moment, so if there are several worms in the same hdf5 file. only the first one will be used.
